import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, "../../..")
const contractRoot = path.resolve(here, "..")
const localeDir = path.join(contractRoot, "locales")
const codes = ["en", "sw", "es", "fr", "pt", "ar", "hi", "zh"]
const dictionaries = Object.fromEntries(codes.map((code) => [code, JSON.parse(fs.readFileSync(path.join(localeDir, `${code}.json`), "utf8"))]))
const terminology = JSON.parse(fs.readFileSync(path.join(contractRoot, "terminology.json"), "utf8"))
const englishKeys = Object.keys(dictionaries.en).sort()
const placeholders = (value) => [...String(value).matchAll(/\{([a-zA-Z][a-zA-Z0-9_]*)\}/g)].map((match) => match[1]).sort()

for (const code of codes) {
  const keys = Object.keys(dictionaries[code]).sort()
  if (JSON.stringify(keys) !== JSON.stringify(englishKeys)) throw new Error(`${code} locale keys do not match English`)
  for (const key of englishKeys) {
    if (JSON.stringify(placeholders(dictionaries[code][key])) !== JSON.stringify(placeholders(dictionaries.en[key]))) {
      throw new Error(`${code}:${key} placeholders do not match English`)
    }
    const lower = String(dictionaries[code][key]).toLocaleLowerCase(code)
    for (const banned of terminology[code] || []) {
      if (lower.includes(String(banned).toLocaleLowerCase(code))) throw new Error(`${code}:${key} contains prohibited product language: ${banned}`)
    }
  }
}

const ts = `// GENERATED by packages/product-contracts/scripts/generate-locales.mjs. Do not edit.\n` +
  `export const supportedLocales = ${JSON.stringify(codes)} as const\n` +
  `export type SupportedLocale = (typeof supportedLocales)[number]\n` +
  `export const messages = ${JSON.stringify(dictionaries, null, 2)} as const\n` +
  `export type MessageKey = keyof typeof messages.en\n`
fs.writeFileSync(path.join(root, "lib/i18n/generated.ts"), ts)

const dartEscape = (value) => String(value).replaceAll("\\", "\\\\").replaceAll("'", "\\'").replaceAll("\n", "\\n").replace(/\{([a-zA-Z][a-zA-Z0-9_]*)\}/g, "@$1")
const dartMaps = codes.map((code) => {
  const entries = englishKeys.map((key) => `    '${dartEscape(key)}': '${dartEscape(dictionaries[code][key])}',`).join("\n")
  return `  '${code}': <String, String>{\n${entries}\n  },`
}).join("\n")
const dart = `// GENERATED by chatandtip-web/packages/product-contracts/scripts/generate-locales.mjs. Do not edit.\n` +
  `const Map<String, Map<String, String>>\nsharedProductLocales = <String, Map<String, String>>{\n${dartMaps}\n};\n`
const flutterOutput = path.resolve(root, "../chatandtip/lib/languages/generated/shared_product_locales.dart")
fs.mkdirSync(path.dirname(flutterOutput), { recursive: true })
fs.writeFileSync(flutterOutput, dart)

console.log(`Validated ${englishKeys.length} keys across ${codes.length} locales and generated TypeScript + Dart dictionaries.`)
